bash testdeeplabv3.sh   
bash testdetr.sh     
bash testefficientnetv2.sh      
bash testfaster_rcnn.sh    
bash testfastseg-large.sh      
bash testfastseg-small.sh      
bash testmask_rcnn.sh 
bash testmobile_net_v2.sh  
bash testmobile_net_v3.sh        
bash testmobile_sam.sh       
bash testmobilevit.sh     
bash testresnet_50.sh   
bash testsam.sh     
bash testswin_int8.sh       
bash testunet_camvid.sh       
bash testyolov5l.sh    
bash testyolov5s.sh   
bash testyolov8l.sh  
bash testyolov8s.sh   