call .\testdeeplabv3.bat
call .\testdetr.bat
call .\testefficientnetv2.bat
call .\testfaster_rcnn.bat
call .\testfastseg-large.bat
call .\testfastseg-small.bat
call .\testmask_rcnn.bat
call .\testmobile_net_v2.bat
call .\testmobile_net_v3.bat
call .\testmobile_sam.bat
call .\testmobilevit.bat
call .\testresnet_50.bat
call .\testsam.bat
call .\testswin_int8.bat
call .\testunet_camvid.bat
call .\testyolov5l.bat
call .\testyolov5s.bat
call .\testyolov8l.bat
call .\testyolov8s.bat